language: objective-c

before_install:
    - brew update || true
    - brew install xctool || true
    - brew upgrade xctool || true
    - gem update --system
    - gem install cocoapods

notifications:
    email:
        on_success: change
        on_failure: always

script: script/cibuild
