language: objective-c

before_install:
    - brew update || true
    - brew install xctool || true
    - brew upgrade xctool || true
    - gem update --system
    - gem install cocoapods

script: script/cibuild Asterism
