language: objective-c
osx_image: xcode7.2
xcode_project: Asterism.xcodeproj
before_install:
    - brew update || true
    - brew install xctool || true
    - brew upgrade xctool || true
    - brew install carthage || true
    - brew upgrade carthage || true

notifications:
    email:
        on_success: change
        on_failure: always

script: 
    carthage update --platform iOS,OSX
    script/cibuild
